version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - run: echo "hello world"
      - run: |
          ./mvnw package
          java -jar target/*.jar

