version: 2.0

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mkdir test-results
      - run: ./mvnw test | circleci tests split --split-by=timings
      - run: ls
      - store_test_results:
          path: target/surefire-reports

#
#  build:
#    docker:
#      - image: circleci/openjdk:stretch
#    steps:
#      - checkout
#      - run: ./mvnw -Dmaven.test.skip=true package

workflows:
  version: 2
#
#  build:
#    jobs:
#      - build

  build-then-test:
    jobs:
      - test
#      - build:
#          requires:
#            - test
