version: 2.1

commands:
  my_restore_cache:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

jobs:
#  test:
#    parallelism: 2
#    docker:
#      - image: circleci/openjdk:stretch
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "pom.xml" }}
#            - v1-dependencies-
#      - run: |
#            ./mvnw \
#            -Dtest=$(for file in $(circleci tests glob "src/test/**/**.java" \
#            | circleci tests split --split-by=timings); \
#            do basename $file \
#            | sed -e "s/.java/,/"; \
#            done | tr -d '\r\n') \
#            -e test verify
#      - store_test_results:
#          path: target/surefire-reports
#      - store_artifacts:
#          path: target/site/jacoco/index.html

  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - my_restore_cache
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "pom.xml" }}
#            - v1-dependencies-
      - run: ./mvnw -Dmaven.test.skip=true package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

#workflows:
#  version: 2
#
#  test-then-build:
#    jobs:
#      - test
#      - build:
#          requires:
#            - test


# BUILD LINK: https://circleci.com/gh/annapamma/spring-petclinic/96#config/containers/0
# Where is the build directory? Is that what a .jar file is?
# Also, does it make sense to test then build? Usually for JavaScript I would test and then build,
# but it seems like for a compiled language the opposite is meant to happen.
