version: 2.0

jobs:
  test:
    parallelism: 2
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: BOOP=(circleci tests glob "src/test/**/**.java") && echo ${BOOP}
      - run: |
          WHAT_IS_THIS=$(for file in $(circleci tests glob "src/test/**/**.java" | circleci tests split --split-by=timings); do basename $file | sed -e "s/.java/,/"; done | tr -d '\r\n')
          echo $WHAT_IS_THIS
      - run: |
          ./mvnw \
          -Dtest=$(for file in $(circleci tests glob "src/test/**/**.java" \
          | circleci tests split --split-by=timings); \
          do basename $file \
          | sed -e "s/.java/,/"; \
          done | tr -d '\r\n') \
          -e test
      - store_test_results:
          path: target/surefire-reports

#
#  build:
#    docker:
#      - image: circleci/openjdk:stretch
#    steps:
#      - checkout
#      - run: ./mvnw -Dmaven.test.skip=true package

workflows:
  version: 2
#
#  build:
#    jobs:
#      - build

  build-then-test:
    jobs:
      - test
#      - build:
#          requires:
#            - test
